import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { Toaster } from "react-hot-toast";
import "./globals.css";

// Use Inter instead of Geist
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <QueryClientProvider client={queryClient}>
          <GoogleOAuthProvider clientId="782621480711-74p66egtbpkbehp27kuenukod2a78cfb.apps.googleusercontent.com">
            {children}
            <Toaster />
            <ReactQueryDevtools />
          </GoogleOAuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
